name: Deploy Changed Files to Salesforce

on:
  push:
    branches:
      - main  # Runs on push to main branch
    paths:
      - 'force-app/main/default/**'  # Triggers only if files inside this folder change
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      # Step 4: Authenticate with Salesforce using JWT
      - name: Authenticate with JWT
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY }}" > server.key
          sf org login jwt \
            --instance-url ${{ vars.INSTANCE_URL }} \
            --client-id ${{ secrets.SF_CONSUMER_SECRET }} \
            --username ${{ secrets.SF_USERNAME }} \
            --jwt-key-file server.key

      # Step 5: Identify changed files
      - name: Identify changed files
        id: changed_files
        run: |
          git diff --name-only HEAD~1 > changed_files.txt || echo "No changes found"
          cat changed_files.txt

      # Step 6: Deploy only changed files
      - name: Deploy changed files to Salesforce
        if: success()
        run: |
          while IFS= read -r file; do
            if [[ -f "$file" ]]; then
              echo "Deploying: $file"
              sf project deploy start --source-dir "$file" --target-org ${{ secrets.SF_USERNAME }}
            fi
          done < changed_files.txt

      # Step 7: Logout from Salesforce
      - name: Logout from Salesforce
        run: |
          sf org logout --target-org ${{ secrets.SF_USERNAME }} --no-prompt

      # Step 8: Success message
      - name: Deployment Successful
        run: echo "✅ Deployment to Salesforce completed successfully!"
